<script setup lang="ts">
import{onMounted,ref}from'vue';import{useRoute,useRouter}from'vue-router';import{ArrowLeft,ArrowRight,Clock,HeartHandshake,MapPin,ShieldAlert,Target}from'@lucide/vue';import{api,apiError}from'@/services/api';import type{ClinicalCase}from'@/types';import{useLocaleStore}from'@/stores/locale'
const route=useRoute(),router=useRouter(),locale=useLocaleStore(),item=ref<ClinicalCase|null>(null),loading=ref(true),starting=ref(false),error=ref('')
async function load(){loading.value=true;error.value='';try{item.value=await api.getCase(String(route.params.id))}catch(e){item.value=null;error.value=apiError(e)}finally{loading.value=false}}
onMounted(()=>void load())
async function start(){starting.value=true;error.value='';try{const session=await api.startSession(String(route.params.id));router.push(`/student/consultation/${session.id}`)}catch(e){error.value=apiError(e,'Could not begin this consultation.')}finally{starting.value=false}}
</script>
<template><div class="page"><RouterLink class="text-button" to="/student/cases"><ArrowLeft :size="16"/>{{locale.t('Back to case library')}}</RouterLink><div v-if="loading" class="loading" role="status"><div class="spinner"></div><span class="sr-only">{{locale.t('Loading')}}</span></div><section v-else-if="error&&!item" class="card empty" role="alert"><h2>{{locale.t('The case could not be loaded.')}}</h2><p>{{error}}</p><button class="button" type="button" @click="load">{{locale.t('Try again')}}</button></section><template v-else-if="item"><header class="case-hero card"><div><div class="page-eyebrow">{{locale.t(item.specialty)}} · {{locale.t(item.difficulty)}}</div><h1 data-no-translate lang="en-AU">{{item.title}}</h1><p data-no-translate lang="en-AU">{{item.subtitle}}</p><div class="case-hero__meta"><span><MapPin :size="15"/>{{locale.t(item.setting)}}</span><span><Clock :size="15"/>{{item.durationMinutes}} {{locale.t('minutes')}}</span></div></div><div class="case-hero__action"><span class="case-number">{{locale.t('Case')}} {{item.id.toString().padStart(2,'0')}}</span><button class="button" :disabled="starting" @click="start">{{starting?locale.t('Preparing patient…'):locale.t('Begin consultation')}}<ArrowRight :size="17"/></button></div></header><div v-if="error" class="alert alert--error error-box" role="alert">{{error}}</div><div class="detail-grid"><section class="card card--padded"><div class="detail-heading"><HeartHandshake/><h2>{{locale.t('Your task')}}</h2></div><p data-no-translate lang="en-AU">{{item.task}}</p><div class="alert"><ShieldAlert :size="17"/>{{locale.t('This is a formative learning activity with a synthetic patient. It is not clinical advice or an examination result.')}}</div></section><section class="card card--padded"><div class="detail-heading"><Target/><h2>{{locale.t('Learning focus')}}</h2></div><ul class="objective-list"><li v-for="objective in item.learningObjectives" :key="objective" data-no-translate lang="en-AU">{{objective}}</li></ul></section></div></template></div></template>
<style scoped>.case-hero{padding:clamp(26px,5vw,52px);display:flex;justify-content:space-between;gap:30px;align-items:flex-end;margin-top:22px;background:linear-gradient(135deg,#fff,#edf6f2)}.case-hero h1{font-size:48px}.case-hero p{color:var(--muted);max-width:620px}.case-hero__meta{display:flex;gap:20px;color:#52655e;font-size:12px}.case-hero__meta span{display:flex;align-items:center;gap:6px}.case-hero__action{display:grid;gap:17px;justify-items:end}.case-number{font:600 15px 'Source Serif 4',serif;color:#84928d}.detail-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px;margin-top:18px}.detail-heading{display:flex;gap:10px;align-items:center;color:var(--green)}.detail-heading h2{color:var(--ink);margin:0}.objective-list{padding:0;list-style:none;margin:14px 0 0;display:grid;gap:12px}.objective-list li{padding-left:23px;position:relative;color:#56645f;font-size:13px}.objective-list li:before{content:'✓';position:absolute;left:0;color:var(--green);font-weight:700}@media(max-width:760px){.case-hero{align-items:flex-start;flex-direction:column}.case-hero h1{font-size:38px}.case-hero__action{justify-items:start;width:100%}.case-hero__action .button{width:100%}.detail-grid{grid-template-columns:1fr}}</style>
